# Somehow, we need this much RAM
org.gradle.jvmargs=-Xmx4G
# This feels like a speed hack. Makes iterative development feel 90x faster.
org.gradle.configureondemand=true
# Allows `remapJar`, `classes` & co. to carry on despite errors.
org.gradle.continue=true

# Officially, this project is stuck on Loom 1.13 with Gradle 8.14.3.
# There's no solution but to ignore the problem, as an IntelliJ capable
# of loading this project in a usable state with updated dependencies,
# at current, seemingly does not exist.
#
# Manifold causes stalls on IntelliJ 2025, and IntelliJ 2022 straight up cannot use Gradle 9.
#
# FIXME: revert to Fabric Loom when possible.
#  Blocker: Gradle 9 on IntelliJ 2022 OR Manifold on IntelliJ 2025
loom.ignoreDependencyLoomVersionValidation=true

# Your project's version
group=gay.ampflower
projectVersion=0.7.0-alpha.1
modrinthId=z23qey0b

# Due to the use of Manifold, this is ultimately meaningless,
# but it makes Stonecutter happy.
vcs_version=fabric-1.21.6
