# Somehow, we need this much RAM
org.gradle.jvmargs=-Xmx4G
# This feels like a speed hack. Makes iterative development feel 90x faster.
org.gradle.configureondemand=true
# Allows `remapJar`, `classes` & co. to carry on despite errors.
org.gradle.continue=true

# Your project's version
group=gay.ampflower
projectVersion=0.7.0-alpha.1
modrinthId=z23qey0b

# Due to the use of Manifold, this is ultimately meaningless,
# but it makes Stonecutter happy.
vcs_version=fabric-1.21.6
