loom.platform = forge
; Ironically, we're dependent on Architectury API despite not using it ourselves.
dependencies.required = obsidianui,architectury-api
loaders = forge

[1.17]
minecraft = 1.17.1
minecraftRequired = [1.17,1.18)
minecraftCompatible = 1.17.1

forge = 1.17.1-37.1.1
obsidianui = 0.1.1+1.17.1

