loom.platform = forge
; Ironically, we're dependent on Architectury API despite not using it ourselves.
dependencies.required = obsidianui,architectury-api
loaders = forge

[1.16.4]
minecraft = 1.16.5
minecraftRequired = [1.16.4,1.17)
minecraftCompatible = 1.16.4,1.16.5

forge = 1.16.5-36.2.34
obsidianui = 0.2.5+mc1.16.5-forge

[1.17]
minecraft = 1.17.1
minecraftRequired = [1.17,1.18)
minecraftCompatible = 1.17.1

forge = 1.17.1-37.1.1
obsidianui = 0.1.1+1.17.1

