loaders = fabric,quilt

[26.1]
; FIXME: make the header also dump into the build.properties
fabric = true

minecraft = 26.1
minecraftRequired = >=26.1-
minecraftCompatible = 26.1-rc-2,26.1,26.1.1,26w14a,26.1.2

spruceui = 10.0.0+26.1
modmenu = 18.0.0-alpha.5
fabricApi = 0.143.12+26.1

yumi-mc-foundation = 1.0.0-beta.2+26.1
