minecraft = com.mojang:minecraft:$minecraftVersion
fabric-loader = net.fabricmc:fabric-loader:fabric-loader

; Manifold
manifold = systems.manifold:manifold:manifold
manifold-rt = systems.manifold:manifold-rt:manifold

manifold-ext = systems.manifold:manifold-ext:manifold
manifold-ext-rt = systems.manifold:manifold-ext-rt:manifold

manifold-props = systems.manifold:manifold-props:manifold
manifold-props-rt = systems.manifold:manifold-props-rt:manifold

manifold-preprocessor = systems.manifold:manifold-preprocessor:manifold

; Manifold extensions... witch edition,
asm = org.ow2.asm:asm:asm
asm-tree = org.ow2.asm:asm-tree:asm

; Mods
spruceui = dev.lambdaurora:spruceui:$spruceui
modmenu = com.terraformersmc:modmenu:$modmenu
fabric-api = net.fabricmc.fabric-api:fabric-api:$fabricApi

; Required for SpruceUI >=1.21.9
yumi-mc-foundation = dev.yumi.mc.core:yumi-mc-foundation:$yumi-mc-foundation

[versions]
fabric-loader = 0.17.+

manifold = 2025.1.27

asm = 9.9

; Plugins
loom = 1.11.+
licenser = 2.1.+
minotaur = 2.+

[dependencies]
minecraft = minecraft

modImplementation = fabric-loader,spruceui,modmenu,fabric-api
include = spruceui,yumi-mc-foundation

compileOnly = manifold-rt,manifold-ext-rt,manifold-props-rt

annotationProcessor = manifold,manifold-ext,manifold-props,manifold-preprocessor
testAnnotationProcessor = manifold,manifold-ext,manifold-props,manifold-preprocessor

[plugins]
loom = fabric-loom:loom
licenser = dev.yumi.gradle.licenser:licenser
minotaur = com.modrinth.minotaur:minotaur

shadow = com.gradleup.shadow:9.2.2
