minecraft = com.mojang:minecraft:$minecraft
mixinextras-common = io.github.llamalad7:mixinextras-common:mixinextras
fabric-loader = net.fabricmc:fabric-loader:fabric-loader

; Forge
forge = net.minecraftforge:forge:$forge
mixinextras-forge = io.github.llamalad7:mixinextras-forge:mixinextras

; Neoforged
neoforge = net.neoforged:neoforge:$neoforge

; Manifold
manifold = systems.manifold:manifold:manifold
manifold-rt = systems.manifold:manifold-rt:manifold

manifold-ext = systems.manifold:manifold-ext:manifold
manifold-ext-rt = systems.manifold:manifold-ext-rt:manifold

manifold-props = systems.manifold:manifold-props:manifold
manifold-props-rt = systems.manifold:manifold-props-rt:manifold

manifold-unchecked = systems.manifold:manifold-exceptions:manifold

manifold-preprocessor = systems.manifold:manifold-preprocessor:manifold

; Manifold extensions... witch edition,
asm = org.ow2.asm:asm:asm
asm-tree = org.ow2.asm:asm-tree:asm

; Flexver
flexver = com.unascribed:flexver-java:1.1.1

; Mods
spruceui = dev.lambdaurora:spruceui:$spruceui
modmenu = com.terraformersmc:modmenu:$modmenu
fabric-api = net.fabricmc.fabric-api:fabric-api:$fabricApi

; Required for SpruceUI >=1.21.9
yumi-mc-foundation = dev.yumi.mc.core:yumi-mc-foundation:$yumi-mc-foundation

; Required for Forge
obsidianui = maven.modrinth:obsidianui:$obsidianui

[versions]
fabric-loader = 0.17.+

manifold = 2025.1.27

asm = 9.9

mixinextras = 0.5.0

; Plugins
fabric-loom = 1.13.+
architectury-loom = 1.11.+
licenser = 2.1.+
minotaur = 2.+

[dependencies]
compileOnly = manifold-rt,manifold-ext-rt,manifold-props-rt

annotationProcessor = manifold,manifold-ext,manifold-props,manifold-preprocessor
testAnnotationProcessor = manifold,manifold-ext,manifold-props,manifold-preprocessor

[fabric]
minecraft = minecraft

modImplementation = fabric-loader,spruceui,modmenu,fabric-api
include = spruceui,yumi-mc-foundation

; Note: only for legacy versions NeoForge does not support.
[forge]
minecraft = minecraft
forge = forge

compileOnly = mixinextras-common
annotationProcessor = manifold-unchecked,mixinextras-common

modImplementation = obsidianui
implementation = mixinextras-forge
include = obsidianui,mixinextras-forge

; I'm not entertaining Forge's broken logic.
; It shall get code and be happy with it.
testAnnotationProcessor = manifold-unchecked

[neoforge]
;implementation = neoforge
minecraft = minecraft
neoForge = neoforge

; TODO: implement basic classifier & attribute support
;modImplementation = spruceui
;include = spruceui,yumi-mc-foundation

[plugins]
loom = fabric-loom:fabric-loom

; Not worth the effort to retool for ForgeGradle.
; Arch Loom works reliably here.
forge = dev.architectury.loom:architectury-loom

; Note: broken 1.21.10 support, will not start reliably.
;  It will build working jars and boot 1.21 reliably tho.
neoforge = dev.architectury.loom:architectury-loom

; Untested - needs extra configuration
;neoforge = net.neoforged.moddev:2.0.115

; Broken - fails to boot dev
;neoforge = net.neoforged.gradle.userdev:7.0.192

licenser = dev.yumi.gradle.licenser:licenser
minotaur = com.modrinth.minotaur:minotaur

shadow = com.gradleup.shadow:9.2.2

machete = io.github.p03w.machete:2.0.1
