modLoader = "javafml"
loaderVersion = "[1,)"
license = "Mozilla Public License 2.0"

issueTrackerURL = "https://github.com/Modflower/music-moods/issues"

[[mods]]
modId = "music_moods"
version = "${version}"
displayName = "Music Moods"

updateJSONURL = "https://api.modrinth.com/updates/${modrinthId}/forge_updates.json"

logoFile = "pack.png"
logoBlur = false

displayURL = "https://mod.ampflower.gay/music-moods"

description = '''
Configure how music & sound are handled.
'''

authors = "Ampflower"
credits = "sisby-folk, HyperPigeon"

displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "music-moods.mixin.json"

[[dependencies.music_moods]]
modId = "minecraft"
mandatory = true
type = "required"

versionRange = "${minecraft_required}"
ordering = "NONE"
side = "CLIENT"
