[versions]
annotations = "23.0.0"
lazydfu = "0.1.3"

# https://github.com/LambdAurora/SpruceUI
spruceui = "4.0.0+1.19"
modmenu = "4.1.1"

# Minecraft
minecraft_version = "1.19.2"
minecraft_required = "1.19-1.19.2"
yarn = "1.19.2+build.28"
quilt_loader = "0.17.+"
quilt_mappings = "1.19.2+build.21"
quilted_fabric_api = "4.0.0-beta.9+0.60.0-1.19.2"

# Plugins
loom = "1.+"
spotless = "5.+"
quiltflower = "1.+"
minotaur = "2.+"

[libraries]
# Minecraft & Quilt
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_version" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

# Yarn mappings if needed.
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

# Libraries
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Mods
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

[bundles]
compileOnly = ["annotations"]
mod_runtime = ["lazydfu"]

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
