[versions]
annotations = "23.0.0"

# https://github.com/LambdAurora/SpruceUI
spruceui = "5.0.0+1.20"
modmenu = "7.0.1"

# Minecraft
minecraft_version = "1.20"
minecraft_required = ">=1.20 <=1.20.1"
fabric_loader = "0.15.+"
fabric_api = "0.83.0+1.20"

# Plugins
loom = "1.+"
spotless = "5.+"
quiltflower = "1.+"
minotaur = "2.+"

[libraries]
# Minecraft & Quilt
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft_version" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

# Libraries
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# Mods
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

[bundles]
compileOnly = ["annotations"]
mod_runtime = []

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
