name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build and publish with Gradle
        run: ./gradlew build modrinth --no-daemon
        env:
          BUILD_RELEASE: ${{github.event.prelease == false}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH}}
          CHANGELOG: ${{ github.event.release.body }}
      - name: Attest build artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'versions/*/build/libs/*.jar'
      - name: Upload releases
        if: ${{ always() }}
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'versions/*/build/libs/*'
          repo-token: ${{secrets.GITHUB_TOKEN}}
      - name: Upload build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: music-moods-artifacts
          path: |
            versions/*/build/libs
            build/reports
            created_attestation_paths.txt
